# Generated by Django 5.2.5 on 2025-08-18 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0003_alter_userprofile_country_alter_userprofile_county_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="kyc_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="kyc_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=120, verbose_name="Display name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=140, unique=True, verbose_name="Slug"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
                (
                    "payout_provider",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Payout provider"
                    ),
                ),
                (
                    "payout_account_id",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Payout account id"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
            },
        ),
    ]
