# Generated by Django 5.2.5 on 2025-08-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("profiles", "0004_userprofile_is_seller_userprofile_kyc_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Published at"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="review_notes",
            field=models.TextField(blank=True, verbose_name="Review notes"),
        ),
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending review"),
                    ("PUBLISHED", "Published"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                max_length=12,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Submitted at"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["status"], name="catalog_lis_status_fb7f45_idx"),
        ),
    ]
