# Generated by Django 5.2.5 on 2025-08-19 01:25

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_listing_published_at_listing_review_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "EUR"), ("USD", "USD"), ("GBP", "GBP")],
                default="EUR",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
    ]
