# Generated by Django 5.2.5 on 2025-08-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_listing_country_listing_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "EUR"),
                    ("USD", "USD"),
                    ("GBP", "GBP"),
                    ("AED", "AED"),
                    ("SAR", "SAR"),
                    ("JPY", "JPY"),
                    ("CNY", "CNY"),
                    ("INR", "INR"),
                    ("AUD", "AUD"),
                    ("CAD", "CAD"),
                    ("CHF", "CHF"),
                    ("SEK", "SEK"),
                    ("NOK", "NOK"),
                    ("DKK", "DKK"),
                    ("TRY", "TRY"),
                ],
                default="EUR",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="Item code / SKU"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="Variant code"
            ),
        ),
    ]
