# Generated by Django 5.2.5 on 2025-08-19 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_listing_currency_alter_product_sku_and_more"),
        ("profiles", "0004_userprofile_is_seller_userprofile_kyc_approved_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Product group",
                "verbose_name_plural": "Product groups",
            },
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="product",
            name="base_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Base price",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("slug", "parent"), name="uniq_slug_per_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("slug",),
                name="uniq_root_slug",
            ),
        ),
        migrations.AddField(
            model_name="productgroup",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="catalog.product"
            ),
        ),
        migrations.AddField(
            model_name="productgroup",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_groups",
                to="profiles.vendor",
                verbose_name="Vendor",
            ),
        ),
    ]
