# Generated by Django 5.2.5 on 2025-08-19 04:04

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_productgroup_alter_category_unique_together_and_more"),
        ("profiles", "0004_userprofile_is_seller_userprofile_kyc_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="vendor",
        ),
        migrations.AddField(
            model_name="property",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="floor",
            field=models.CharField(blank=True, max_length=20, verbose_name="Floor"),
        ),
        migrations.AddField(
            model_name="property",
            name="furnished",
            field=models.BooleanField(default=False, verbose_name="Furnished"),
        ),
        migrations.AddField(
            model_name="property",
            name="heating",
            field=models.CharField(blank=True, max_length=80, verbose_name="Heating"),
        ),
        migrations.AddField(
            model_name="property",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Postal code"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("APARTMENT", "Apartment"),
                    ("HOUSE", "House"),
                    ("LAND", "Land"),
                    ("COMMERCIAL", "Commercial"),
                ],
                default="APARTMENT",
                max_length=16,
                verbose_name="Property type",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="purpose",
            field=models.CharField(
                choices=[("SALE", "For sale"), ("RENT", "For rent")],
                default="SALE",
                max_length=8,
                verbose_name="Purpose",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="year_built",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Year built"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("PRODUCT", "Product"),
                    ("SERVICE", "Service"),
                    ("CAR", "Car"),
                    ("PROPERTY", "Real Estate"),
                ],
                max_length=16,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="is_for_rent",
            field=models.BooleanField(
                default=False, verbose_name="For rent (deprecated)"
            ),
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=80, verbose_name="Make")),
                ("model", models.CharField(max_length=80, verbose_name="Model")),
                ("year", models.PositiveIntegerField(verbose_name="Year")),
                (
                    "made_in",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True, verbose_name="Made in"
                    ),
                ),
                (
                    "mileage_km",
                    models.PositiveIntegerField(default=0, verbose_name="Mileage (km)"),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[("MANUAL", "Manual"), ("AUTOMATIC", "Automatic")],
                        max_length=12,
                        verbose_name="Transmission",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PETROL", "Petrol"),
                            ("DIESEL", "Diesel"),
                            ("HYBRID", "Hybrid"),
                            ("ELECTRIC", "Electric"),
                            ("LPG", "LPG"),
                            ("CNG", "CNG"),
                            ("OTHER", "Other"),
                        ],
                        max_length=12,
                        verbose_name="Fuel type",
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Body type"
                    ),
                ),
                (
                    "doors",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Doors"
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=40, verbose_name="Color"),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("NEW", "New"), ("USED", "Used")],
                        default="USED",
                        max_length=8,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "vin",
                    models.CharField(blank=True, max_length=32, verbose_name="VIN"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Price"
                    ),
                ),
                (
                    "negotiable",
                    models.BooleanField(default=False, verbose_name="Negotiable"),
                ),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="Images"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cars",
                        to="profiles.vendor",
                        verbose_name="Vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
        migrations.DeleteModel(
            name="RentalItem",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
